# Generated by Django 4.2.4 on 2023-08-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_attachment_rename_timestamp_notice_posted_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='posted_date',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='attachments',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
