# Generated by Django 4.2.4 on 2023-08-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_attachment_notice_attachments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='attachments',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.AddField(
            model_name='notice',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
